### ISSUE TITLE
Use local copies of resources instead of dynamic download

### ISSUE THREAD

**Issue by vsmalladi** [PacificBiosciences/pb-human-wgs-workflow-wdl#65]
Instead of downloading the data from clinvar, can we just cache the file? The snakemake code was essentially caching this, but without a shared filesystem, makes more sense to provide the file as a resource rather than download it.

There are potentially a few other cases like this as well: ensembl, tandem-genotypes... maybe others?

**Comment by byoo** [comment]
That would be fine to use local resources for all(hosted in our own container?). I can see the ensembl ftp sites. But tandem-genotypes looks to use files in a container and code changes don't seem to be needed, correct?

**Comment by vsmalladi** [comment]
That is the idea. Let me change them to be able to use either

Tandem genotypes uses files in a container so no changes.

Seems to be limited to:
clinvar_lookup
gff

I will update the code so it doesn't do a url look up but a file in the container.
