### ISSUE TITLE
Error response from the container registry, https://pacbio.azurecr.io

### ISSUE THREAD

**Issue by byoo** [PacificBiosciences/pb-human-wgs-workflow-wdl#80]
Hello! We had been able to use the pipeline in production. But the last pipelining had the problem with the container registry below. Can you help with the issue?

> Error response from daemon: Head "https://pacbio.azurecr.io/v2/pb-human-wgs-workflow/manifests/latest": error parsing HTTP 403 response body: unexpected end of JSON input: ""

**Comment by williamrowell** [comment]
Hi Byunggil, we have a temporary outage and we're working to address it.  Hoping to have it taken care today.

**Comment by byoo** [comment]
Thanks a lot, @williamrowell!

**Comment by byoo** [comment]
@williamrowell,
Would you let us know when the issue is resolved? Thanks!

**Comment by williamrowell** [comment]
I definitely will let you know as soon as it's fixed.

**Comment by williamrowell** [comment]
@byoo Sorry for the delay. We're working to avoid this kind of downtime in the future.

Can you verify that service has been restored?

**Comment by byoo** [comment]
@williamrowell It looks good and the first set of tasks finished successfully. I will report if there are any issues. Thanks!

**Comment by williamrowell** [comment]
@byoo Thanks for verifying, and sorry for the downtime.
